<?php

/** @var \AddressWiseExtension\AddressWise\Block\Checkout $block */

$clientToken = $block->getClientToken();
$isEnabled = $block->isEnabled(); // Store the isEnabled value in a variable

?>

<?php if ($isEnabled): ?>

    <div class="af-popup">
        <table class="af-option"></table>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "AddressWiseExtension_AddressWise/js/addresswise": {
                    "client_token": "<?= $block->escapeJs($clientToken); ?>",
                    "enabled": <?= ($isEnabled ? 'true' : 'false'); ?>
        }
    }
}
    </script>
<?php endif ?>
